import type { Metadata } from "next";
import "./globals.css";
import ScrollTop from "@/components/ui/scroll-top-button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <ScrollTop />
      </body>
    </html>
  );
}
